export type Stage =
  | "PROFILE_BUILDING"
  | "DISCOVERING_UNIVERSITIES"
  | "FINALIZING_UNIVERSITIES"
  | "PREPARING_APPLICATIONS";

export const STAGES: Stage[] = [
  "PROFILE_BUILDING",
  "DISCOVERING_UNIVERSITIES",
  "FINALIZING_UNIVERSITIES",
  "PREPARING_APPLICATIONS",
];
